### ISSUE TITLE
General: 박스의 크기가 정확하게 똑같아야 할까요?

### ISSUE THREAD

**Issue by dusskapark** [bridgedxyz/ui-dataset#3]
<img width="400" alt="Screen Shot 2020-11-17 at 2 23 39 PM" src="https://user-images.githubusercontent.com/4177529/99634313-9d1df280-2a83-11eb-9ea9-c184e3e7b606.png">

예를 들어 작은 아바타의 경우, 같은 크기의 박스를 그리는 것은 현실적으로 어렵습니다. (Figma도 아니고..)

**Comment by dusskapark** [comment]
그런데 여기저기 찾아보니깐 박스의 크기가 모델의 성능에 큰 영항을 주지는 않는다고 합니다. 걱정말고 컴포넌트를 라벨링하시죠.

**Comment by softmarshmallow** [comment]
It ain't implemented yet, but relflect detection (rule + vision detection) uses dedicated size of the element. It might be re-labelled for element-level labelling.
https://github.com/bridgedxyz/reflect-detection/tree/main/lib/avatar.detection


But as you said It won't be any problem for now!

Closing.
